// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2qJQe7XtevzmGyxo6De72HtrTJmw3ekM',
    appId: '1:49381842735:web:e533f002d10d5b6b534bda',
    messagingSenderId: '49381842735',
    projectId: 'flutter2-race-tracking-app',
    authDomain: 'flutter2-race-tracking-app.firebaseapp.com',
    databaseURL: 'https://flutter2-race-tracking-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter2-race-tracking-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF-5clzJru4VMsibrol81JC-zb6UjqprQ',
    appId: '1:49381842735:android:933aa4807f4e0552534bda',
    messagingSenderId: '49381842735',
    projectId: 'flutter2-race-tracking-app',
    databaseURL: 'https://flutter2-race-tracking-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter2-race-tracking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP4cry7GK-LcycJZDYJEti0wGLRIY0rB8',
    appId: '1:49381842735:ios:25dda1f153397567534bda',
    messagingSenderId: '49381842735',
    projectId: 'flutter2-race-tracking-app',
    databaseURL: 'https://flutter2-race-tracking-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter2-race-tracking-app.firebasestorage.app',
    iosBundleId: 'com.example.raceTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP4cry7GK-LcycJZDYJEti0wGLRIY0rB8',
    appId: '1:49381842735:ios:25dda1f153397567534bda',
    messagingSenderId: '49381842735',
    projectId: 'flutter2-race-tracking-app',
    databaseURL: 'https://flutter2-race-tracking-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter2-race-tracking-app.firebasestorage.app',
    iosBundleId: 'com.example.raceTrackingApp',
  );
}
